version: '3.8'

services:
  mongodb:
    image: mongo:7.0.9
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

volumes:
  mongo-data:
