openapi: 3.0.0
info:
  title: URL Shortener Service
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /url:
    post:
      tags:
        - 'URL'
      summary: Shortens the provided URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL to be shortened
                  example: https://www.example.com
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The shortened URL
                    example: https://localhost:3000/aksjd823
        '400':
          description: Bad request (e.g., invalid JSON or missing URL)
