openapi: 3.0.0
info:
  title: URL Shortener Service
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /url:
    post:
      tags:
        - 'URL'
      summary: Shortens the provided URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL to be shortened
                  example: https://www.example.com
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The shortened URL
                    example: https://localhost:3000/aksjd823
        '400':
          description: Bad Request
    get:
      tags:
        - 'URL'
      summary: Get all shortened URLs
      parameters:
        - in: query
          name: limit
          required: false
          description: Maximum number of objects to return
          schema:
            type: integer
            minimum: 10 # Optional: Set minimum allowed value
        - in: query
          name: skip
          required: false
          description: Number of objects to skip before starting results
          schema:
            type: integer
            minimum: 0 # Optional: Set minimum allowed value
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array # Response is an array
                items:
                  type: object # Each item in the array is an object
                  # Define the properties of the object here
                  properties:
                    original: # Example property name
                      type: string
                      description: Original URL
                      example: https://www.google.com
                    alias:
                      type: string
                      description: URL alias
                      example: suKX7hF

  /{alias}:
    get:
      tags:
        - 'URL'
      summary: Gets the original URL
      parameters:
        - in: path
          name: alias
          schema:
            type: string
          required: true
          description: Alias of a shortened URL
          example: suKX7hF
      responses:
        '301':
          description: Moved Permanently
          headers:
            Location:
              description: URL to redirect to
              schema:
                type: string
                example: https://www.google.com
        '404':
          description: Not Found
